name: Node.js CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  prepare:
    runs-on: ubuntu-latest

    steps:
      - name: Connect Using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/revamp-backend
            git pull origin master

  deploy:
    needs: prepare
    runs-on: ubuntu-latest

    steps:
      - name: Remove Conflicting Docker Deps
        run: |
          sudo apt-get remove docker docker-engine docker.io containerd runc
          sudo apt-get purge docker-ce docker-ce-cli containerd.io
          sudo rm -rf /var/lib/docker

      - name: Resolve Unmet Dependencies
        run: |
          sudo apt-get update
          sudo apt-get upgrade
          sudo apt-get dist-upgrade
          sudo apt-get autoremove
          sudo apt-get autoclean

      - name: Install docker using Docker's Official Script
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh

      - name: Install docker compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Run Docker Daemon
        run: sudo systemctl enable docker --now

      - name: Stop Running Instance
        run: |
          sudo docker ps | grep revamp-backend | awk '{ command = "docker stop " $1; system(command) }'

      - name: Build and Run Docker Container
        run: |
          sudo docker build -t revamp-backend .
          sudo docker run -p 8000:8000 revamp-backend &
