name: Node.js CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  prepare:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/revamp-backend
            git pull origin master

  setup-docker:
    needs: prepare
    runs-on: ubuntu-latest

    steps:
      - name: Install Docker
        run: |
          sudo snap install docker
          sudo apt install docker.io -y
          sudo systemctl enable docker --now

  deploy:
    needs: setup-docker
    runs-on: ubuntu-latest

    steps:
      - name: Stop Running Instance
        run: |
          sudo docker ps | grep revamp-backend | awk '{ command = "docker stop " $1; system(command) }'

      - name: Build and Run Docker Container
        run: |
          sudo docker build -t revamp-backend .
          sudo docker run -p 8000:8000 revamp-backend &
