name: Node.js CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  prepare:
    runs-on: ubuntu-latest

    steps:
      - name: Connect Using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/revamp-backend
            git pull origin master

  deploy:
    needs: prepare
    runs-on: ubuntu-latest
